version: "3.5"
services:
  #services properties
  tariff-service:
    depends_on:
      - tariffDb
    ports:
      - 80:80
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://tariffDb:5432/tariffDb
      QUARKUS_DATASOURCE_DB-KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: tariffDb
      QUARKUS_DATASOURCE_PASSWORD: tariffDb

  #db properties
  tariffDb:
    ports:
      - 5433:5432
    image: postgres:12
    environment:
      POSTGRES_DB: tariffDb
      POSTGRES_USER: tariffDb
      POSTGRES_PASSWORD: tariffDb

